create game and select sport
kr396/PlayAmigos pull request #3
Opened 2024-04-03 04:53 UTC by RathodSagar18

create game=>ui complete logic 90%

selectsport=>ui and logic 100% completed

2024-04-03 05:15 UTC, kr396 requested changes

2024-04-03 05:15 UTC, kr396 commented on src/components/ThemeButton.tsx
> +  disabled,
Where are you using this?

2024-04-03 05:15 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +    if (route.params && route.params.selectedSport) {
Instead of `route.params && route.params.selectedSport` you can diretly write` route.params?.selectedSport`

2024-04-03 05:15 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +  const onSelectDateTime = (date: Date, time: boolean) => {
instead of `time:boolead` kindly pass `type: 'time' | 'date'`

2024-04-03 05:15 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +            selectedDate.toString().split(' ').slice(0, 4).join(' '),
check date-fns library use that to formate date and time

2024-04-03 05:15 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +            selectedDate.toString().split(' ').slice(4, 5).join(' '),
Use date-fns library

2024-04-03 05:15 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +      <ThemeButton title={'Create Game'} style={styles.createButton} />
Add this button inside scrollview

2024-04-03 05:15 UTC, kr396 commented on src/screens/CreateGame/type.ts
> +export type Game = {
Where are you using this?

2024-04-03 05:15 UTC, kr396 commented on src/screens/SelectSport/index.tsx
> +  const sports: Sport[] = useAppSelector(getSportsList);
Remove time from here. It will automatically work based on return type

2024-04-03 05:15 UTC, kr396 commented on src/screens/SelectSport/index.tsx
> +        selectedSport === item && styles.selectedItemContainer,
Move this style to stylesheet as we discussed last day

2024-04-09 11:57 UTC, kr396 requested changes

2024-04-09 11:57 UTC, kr396 commented on src/components/LocationPopup.tsx
> +    {name: 'Location1', icon: <LocationPinIcon />},
Remove icon from here, For all items icon will be same. So, Add that into renderItem

2024-04-09 11:57 UTC, kr396 commented on src/components/LocationPopup.tsx
> +        <ScrollView>
Remove scrollview

2024-04-09 11:57 UTC, kr396 commented on src/config/images.ts
> +  MySportsIcon: require('../assets/images/bottomTabs/mysports.png'),
rename this "m" should be small case and image name should be mySports.png "S" small

2024-04-09 11:57 UTC, kr396 commented on src/config/svgs.ts
> +export {default as Location} from '../assets/svgs/common/location.svg';
Add Icon suffix for icons like "LocationIcon"

2024-04-09 11:57 UTC, kr396 commented on src/navigation/MySportsStack.tsx
> +
Remove this extra lines

2024-04-09 11:57 UTC, kr396 commented on src/navigation/PlayStack.tsx
> +      {/* <Stack.Screen name="CreateGame" component={CreateGame} /> */}
Remove these both commented lines if not required

2024-04-09 11:57 UTC, kr396 commented on src/navigation/Router.tsx
> +            <Stack.Screen name="MySports" component={MySports}/>
Why do we need MySports here? Remove from here

2024-04-09 11:57 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +  const [openGame, setOpenGame] = useState(false);
What is this openGame users for? Give appropriate name.

2024-04-09 11:57 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +  const [sliderVisible, setSliderVisible] = useState(false);
give appropriate name

2024-04-09 11:57 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +  const [sliderValues, setSliderValues] = useState<number[]>([1, 5]);
give appropriate name

2024-04-09 11:57 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +  const bottomSheetRef = useRef<BottomSheet>(null);
give appropriate name

2024-04-09 11:57 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +    console.log('Navigating to MySports screen...');
remove log

2024-04-09 11:57 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +  const openBottomSheet = () => {
give appropriate name

2024-04-09 11:57 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +  const handleOpenGameToggle = () => {
give appropriate name

2024-04-09 11:57 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +            {sliderVisible && (
combine all these 3 conditions

2024-04-09 11:57 UTC, kr396 commented on src/screens/MySports/index.tsx
> +        ListFooterComponent={
move this to function

2024-04-09 16:27 UTC, kr396 requested changes

2024-04-09 16:27 UTC, kr396 commented on src/config/images.ts
> +  MySportsIcon: require('../assets/images/bottomTabs/mySports.png'),
"M" should be small in MySportsIcon

2024-04-09 16:27 UTC, kr396 commented on src/screens/CreateGame/index.tsx
> +  const [openGameSkill, setOpenGameSkill] = useState(false);
this nam sis wrong should be gameType

2024-04-10 04:32 UTC, RathodSagar18 commented on src/components/ThemeButton.tsx
> +  disabled,
i am using this in inside of SelectSport themButton as a disable prop

2024-04-12 10:48 UTC, kr396 requested changes

2024-04-12 10:48 UTC, kr396 commented on src/navigation/Router.tsx
> +            <Stack.Screen name="ChangePassword" component={ChangePassword} />
Why are you adding change Password here? It should be in Profile stack

2024-04-12 10:48 UTC, kr396 commented on src/navigation/types.ts
> +  ChangePassword: undefined;
Remove above 3 Screen from here and add into appropriate Stack

2024-04-12 10:48 UTC, kr396 commented on src/screens/ChangePassword/index.tsx
> +
remove this extra line

2024-04-12 10:48 UTC, kr396 commented on src/screens/ChangePassword/index.tsx
> +
Remove extra line

2024-04-12 10:48 UTC, kr396 commented on src/screens/ChangePassword/index.tsx
> +        text2: 'Failed to change password. Please try again.',
Remove this toast

2024-04-12 11:47 UTC, kr396 requested changes

2024-04-12 11:47 UTC, kr396 commented on src/navigation/Router.tsx
> +            <Stack.Screen name="SelectSport" component={SelectSport} />
Why this file is here? It should be in MySportsStack

2024-04-13 04:32 UTC, merged