work on api changes
kr396/PlayAmigos pull request #6
Opened 2024-04-30 14:03 UTC by RathodSagar18

2024-04-30 15:00 UTC, kr396 approved these changes

2024-04-30 15:00 UTC, kr396 commented on .yarn/install-state.gz
remove this file from MR

2024-04-30 15:00 UTC, kr396 commented on src/components/GameBasicCard.tsx
> +  const getRelativeDate = (dateStr: string): string => {
move this function to utils. Import and user that

2024-04-30 15:00 UTC, kr396 commented on src/components/GameCard.tsx
> +  const getRelativeDate = (dateStr: string): string => {
import from util and use

2024-04-30 15:00 UTC, kr396 commented on src/components/RequestQueryPopup.tsx
> +  placeholder,
Why do we need placeholder in props? This will be same for all. Use static placeholder in this file itself

2024-04-30 15:00 UTC, kr396 commented on src/components/RequestQueryPopup.tsx
> -            placeholder="Send a message to the host along with your requests"
undo this change

2024-04-30 15:00 UTC, kr396 commented on src/components/RequestQueryPopup.tsx
> +            title={buttonText}
Why this button text is dynamic?

2024-04-30 15:00 UTC, kr396 commented on src/navigation/ProfileStack.tsx
> +      <Stack.Screen name="CommanReview" component={CommanReview} />
What is this used for "CommonReview"

2024-04-30 15:00 UTC, kr396 commented on src/screens/CommanReview/index.tsx
What is this file used for?

2024-04-30 15:00 UTC, kr396 commented on src/screens/GameDetails/index.tsx
>    const joinGame = async () => {
Can we move this API calling into popup component ?

2024-04-30 15:00 UTC, kr396 commented on src/screens/Home/index.tsx
> +          data={[
Add TODO here

2024-04-30 15:00 UTC, kr396 commented on src/screens/Login/index.tsx
> +      console.log('response', response);
remove log

2024-04-30 15:00 UTC, kr396 commented on src/screens/MySports/index.tsx
> +        data={[
Add too here. Also why Avatar list is passed as children? It should be available into GameCard component

2024-05-01 06:23 UTC, RathodSagar18 commented on src/components/RequestQueryPopup.tsx
> +  placeholder,
i have created common popup component for request query and join game that reason i updated placeholder as props

2024-05-01 06:25 UTC, RathodSagar18 commented on src/components/RequestQueryPopup.tsx
> +            title={buttonText}
i have created common popup component for request query and join game that reason i am using button text dynamic

2024-05-01 06:27 UTC, RathodSagar18 commented on src/navigation/ProfileStack.tsx
> +      <Stack.Screen name="CommanReview" component={CommanReview} />
for privacy policy screen

2024-05-01 06:27 UTC, RathodSagar18 commented on src/screens/CommanReview/index.tsx
for privacy policy screen

2024-05-01 06:29 UTC, RathodSagar18 commented on src/screens/GameDetails/index.tsx
>    const joinGame = async () => {
popup component is common for request query and join game that reason i am not updating api in popup

2024-05-09 12:53 UTC, kr396 requested changes

2024-05-09 12:53 UTC, kr396 commented on src/components/JoinGamePopup.tsx
> +
API call should be in this file for join game

2024-05-09 12:53 UTC, kr396 commented on src/components/JoinGamePopup.tsx
> +  onButtonPress: () => void;
we don't need many props from this

2024-05-09 12:53 UTC, kr396 commented on src/components/JoinGamePopup.tsx
> +    Height: 110,
why Height is in Capital?

2024-05-09 12:53 UTC, kr396 commented on src/components/LocationPopup.tsx
> +    color: colors.black,
use typography color

2024-05-09 12:53 UTC, kr396 commented on src/components/RequestGameCard.tsx
> +  firstname: string;
use camel case

2024-05-09 12:53 UTC, kr396 commented on src/navigation/ProfileStack.tsx
> +      <Stack.Screen name="Webview" component={Webview} />
This should be CommanWebView

2024-05-09 12:53 UTC, kr396 commented on src/redux/commonSlice/gameSlice.ts
> +    builder.addCase(joinGameAPI.rejected, (state, action) => {});
Remove all this 4 cases

2024-05-09 12:53 UTC, kr396 commented on src/screens/AllQueries/index.tsx
> +  const renderQuerys = ({item}) => {
spelling is wrong

2024-05-09 12:53 UTC, kr396 commented on src/screens/Profile/index.tsx
> +    navigation.navigate('Webview');
As I told you 2 times you have to pass "title" and "url" as params and use that into CommonWebView screen

2024-05-09 12:53 UTC, kr396 commented on src/screens/Request/styles.ts
> +    marginHorizontal: 16,
use from margins

2024-05-09 12:53 UTC, kr396 commented on src/screens/SignUp/index.tsx
> +        password: password,
why these showing 2 times ? Remove which is not required

2024-05-11 12:20 UTC, merged